inherit_gem:
  lint-project: config/rubocop.yml

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  Include:
    - '.tools/**/*.rb'
    - '.tools/**/*.rake'
    - '.tools/**/*.gemspec'
  Exclude:
    - 'concat/**/*'
    - 'debconf/**/*'
    - 'reboot/**/*'
    - 'stdlib/**/*'
    - 'timezone/**/*'
    - 'vendor/bundle/**/*'
    # ERB source must be rendered before it becomes valid Ruby.
    - '**/templates/**/*'
