# Managed by puppet
Banner /etc/issue.net
ClientAliveCountMax 2
ClientAliveInterval <%= @idle_timeout %>
DebianBanner no
HostKeyAlgorithms <%= @host_key_algorithms_str %>
KbdInteractiveAuthentication no
LoginGraceTime 120
LogLevel VERBOSE
MaxAuthTries 3
PasswordAuthentication no
PermitEmptyPasswords no
PermitRootLogin <%= @permit_root_login_correct %>
<% if !@systemd_socket -%>
Port <%= @port %>
<% if ! @port_alternative.nil? -%>
Port <%= @port_alternative %>
<% end -%>
<% end -%>
Protocol 2
PrintLastLog yes
PrintMotd no
PubkeyAuthentication yes
StrictModes yes
SyslogFacility AUTH
TCPKeepAlive no
UsePAM yes
X11Forwarding no
<% if ! @allow_users_str.empty? -%>
Match LocalPort <%= @port %>
    AllowUsers <%= @allow_users_str %>
<% end -%>
<% if (! @port_alternative.nil? && ! @port_alternative_allow_users_str.empty?) -%>
Match LocalPort <%= @port_alternative %>
    AllowUsers <%= @port_alternative_allow_users_str %>
<% end -%>
<% if ! @password_authentication_users_str.empty? -%>
Match User <%= @password_authentication_users_str %>
    PasswordAuthentication yes
<% end -%>
