#!/bin/sh

# Managed by puppet

# Check if mail is available
MAIL=/usr/bin/mail
test -x $MAIL || exit 1

# Get information
USER=$(whoami)
NOW=$(date)

# Try to get IP
TMP_IP=$(w --no-header $USER | awk '{print $3}' )
if [ -n $TMP_IP ]; then
    IP="$TMP_IP"
else
    IP="UNKNOWN"
fi

# Send message
printf '%b\n' "User $USER logged into the <%= @server_fdqn %> at $NOW\nIP: $IP" | $MAIL -s "Audit login $USER" -r "audit@<%= @server_fdqn %>" "<%= @mail_to %>"

# Show message 
printf "Your IP ($IP), login time ($NOW) and username ($USER) have been registered and sent to the server administrator.\n"
