#!/bin/sh

# Managed by puppet

# Check if mail is available
MAIL=/usr/bin/mail
test -x $MAIL || exit 1

# Current date
NOW=$(date)

# Try to get IP
if [ -n "$(echo $SSH_CLIENT)" ]; then
    IP=$(echo $SSH_CLIENT| awk '{ print $1}')
elif [ -n "$(echo $SSH_CONNECTION)" ]; then
    IP=$(echo $SSH_CONNECTION| awk '{ print $1}')
else
    IP="UNKNOWN"
fi

# Send message
printf '%b\n' "User $USER logged into the <%= @server_fdqn %> at $NOW\nIP: ${IP}" | $MAIL -s "Audit login $USER" -r "audit@<%= @server_fdqn %>" "<%= @mail_to %>"

# Show message 
printf "Your IP, login time and username have been registered and sent to the server administrator.\n"