#!/bin/sh

# Managed by puppet

# Check if RX buffer tool is available
RXBUFFERTOOL=/usr/local/sbin/rxbuffer
test -x $RXBUFFERTOOL || exit 0

# Check if interface is not lo
[ "$IFACE" != "lo" ] || exit 0

# Run command
$RXBUFFERTOOL --interface "$IFACE"