#!/bin/sh

# Managed by puppet

# Check if aureport is available
AUREPORTTOOL=/usr/sbin/aureport
test -x $AUREPORTTOOL || exit 1

# Check if aureport is available
MAIL=/usr/bin/mail
test -x $MAIL || exit 1

# Try to get aureport
OUTPUT=$($AUREPORTTOOL -k -ts yesterday 00:00:00 -te yesterday 23:59:59)

# Check if we have valid report
if [ -z "$(echo $OUTPUT | grep "no events of interest were found")" ]; then
    printf '%b\n' "$OUTPUT" | $MAIL -s "Audit report" -r "audit@<%= @server_fdqn %>" "<%= @mail_to %>"
fi